# This file allows a build on Travis-CI MacOS environment
# Just rename to .travis.yml

language: objective-c
compiler:
  - clang
env:
  global:
    - GMOCK_HOME="$TRAVIS_BUILD_DIR/gmock-1.7.0"
    - DYLD_FALLBACK_LIBRARY_PATH=$GMOCK_HOME/lib/.libs:$GMOCK_HOME/gtest/lib/.libs:$DYLD_FALLBACK_LIBRARY_PATH
before_install:
  #- rvm use ruby-2.0.0-p247
  - brew update
  #- brew reinstall isl011
install:
  - brew install eigen
  - brew install cgal --c++11 --imaging --with-eigen --with-lapack
script:
  - curl -O https://googlemock.googlecode.com/files/gmock-1.7.0.zip
  - unzip gmock-1.7.0.zip
  - cd gmock-1.7.0
  - "./configure"
  - make
  - cd ..
  - "ls $GMOCK_HOME/lib/.libs"
  - "ls $GMOCK_HOME/gtest/lib/.libs"
  - "./build.sh"
after_script:
  - cd build
  - "./unittests"
  - make test
cache:
  - bundler
