language: cpp

os:
  - linux
  - osx

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

# matrix:
#   exclude:
#     - os: osx
#     - compiler: gcc
#     - os: linux
#     - compiler: clang
  # include:
  #   - os: linux
  #     dist: trusty
  #     sudo: required
  #   - os: osx
  #     osx_image: xcode7.2

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" && "CXX" == "gcc" ]]; then
#       sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
#     fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" && "CXX" == "clang" ]]; then
#       wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
#       sudo apt-add-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main";
#     fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./install-linux.sh; fi
  # Install CGAL from source
  - cd $TRAVIS_BUILD_DIR
  - curl -L -o CGAL-4.7.tar.gz https://github.com/CGAL/cgal/archive/releases/CGAL-4.7.tar.gz
  - tar zxvf CGAL-4.7.tar.gz &> install.log
  - cd cgal-releases-CGAL-4.7
  - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_Eigen3=ON -G Ninja .
  - ninja
  - sudo ninja install &> install.log
  - cd ..

script:
  - ./build.sh

after_script:
  - cd build
# GMock with random test order
  - "./unittests --gtest_shuffle"
# CTest
  - ninja test

cache:
  - bundler
  - apt

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/c70e4d2749931f601747
    on_success: change
    on_failure: always
