language: objective-c
compiler: clang
env: std=c++11 stdlib=libc++
before_install:
  - rvm use ruby-2.0.0-p247
  - brew update
  #- brew reinstall isl011
install:
  - brew install eigen
  - brew install cgal --imaging --with-eigen --with-lapack
script: 
  - cmake .
  - make
after_script:
  - make test
cache:
  - bundler
