language: objective-c

before_install:
  # Install homebrew
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
install:
  - brew install cmake
  - brew install eigen
  - brew install cgal --imaging --with-eigen --with-lapack
script: 
  - cmake .
  - make
after_script: make test
cache:
  - bundler
