language: cpp
compiler:
  - gcc
  - clang
before_install: sudo apt-get update
install:
  - sudo apt-get install cmake
  - sudo apt-get install libcgal8
script: 
  - cmake .
  - make
after_script: make test
cache:
  - bundler
  - apt
