# This file builds on the Travis-CI container environment
# Just rename to .travis.yml
#

sudo: false
language: cpp
compiler:
  - gcc
  - clang
env:
  global:
    - GMOCK_HOME="$TRAVIS_BUILD_DIR/gmock-1.7.0"

install:
  - apt-get install -qq libboost-all-dev
  - apt-get install -qq libmpfr-dev
  - apt-get install -qq cmake
  - apt-get install -qq libeigen3-dev
  #- sudo apt-get install -qq ninja-build
  - apt-get install make
  - apt-get install -qq curl
  - apt-get install -qq libgmp3-dev
  - curl -O https://gforge.inria.fr/frs/download.php/file/34149/CGAL-4.5.tar.gz
  - tar zxvf CGAL-4.5.tar.gz &> install.log
  - cd CGAL-4.5
  - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_Eigen3=ON .
  - make
  - make install &>> install.log
script:
  - cd $TRAVIS_BUILD_DIR
  - curl -O https://googlemock.googlecode.com/files/gmock-1.7.0.zip
  - unzip gmock-1.7.0.zip
  - cd gmock-1.7.0
  - "./configure"
  - make
  - cd ..
  #- "./build.sh"
  - mkdir build
  - cd build
  - cmake ..
  - make
after_script:
  #- cd build
  - "./unittests"
  - make test
cache:
  - bundler
  - apt
