language: objective-c

install:
  - brew install cmake
  - brew install eigen
  - brew install cgal --imaging --with-eigen --with-lapack
script: 
  - cmake .
  - make
after_script:
  - make test
cache:
  - bundler
